name: snowflake_flutter_theme
description: Snowflake theme for Flutter
version: 1.2.2+20

publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.3.0
  flutter_riverpod: ^2.6.1
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.16
  gap: ^3.0.1
  logger: ^2.5.0
  riverpod_annotation: ^2.6.1
  slang: ^4.0.0
  slang_flutter: ^4.0.0
  string_validator: ^1.1.0
  toastification: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.4
  slang_build_runner: ^4.0.0

flutter:
  uses-material-design: true
