name: snowflake_flutter_theme
description: Snowflake theme for Flutter
version: 1.0.0+1

publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.19.4 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  gap: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
